server:
  servlet:
    context-path: /
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/attendance
    username: root
    password: system
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  application:
    name: Attendance-Service
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.60:8761/eureka/
 


springdoc:
  api-docs:
    path: /attendance/v3/api-docs    
  swagger-ui:
    path: /attendance/v3
    
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
logging:
  file:
    name: D:\New folder\attendance.log
    
    
attendance:
  monthly:
    csv:
      header: Sno, Employee Id, Employee Name, Month Name, Total Public Holiday, Total Working Day, Paid Leave, Employee Working Day
    